// Select the database to use.
use("FurnitureStore");

db.getCollection("users").insertMany([
  {
    username: "Simarpreet",
    user_email: "simarkang@gmail.com",
    user_password: "simarkang@gmail.com",
    user_telephone: 5197318442,
    user_address: "123 Main St, Toronto, ON",
    user_role: 1,
  },
  {
    username: "Jashanpreet",
    user_email: "jashanpreet@gmail.com",
    user_password: "jashanpreet@gmail.com",
    user_telephone: 5986452123,
    user_address: "569 Oak Avenue, Vancouver, BC",
    user_role: 1,
  },
  {
    username: "Michael Johnson",
    user_email: "michael.johnson@example.com",
    user_password: "pass123word",
    user_telephone: 2345678901,
    user_address: "789 Elm Road, Montreal, QC",
    user_role: 2,
  },
  {
    username: "Emily Brown",
    user_email: "emily.brown@example.com",
    user_password: "secretpass",
    user_telephone: 3456789012,
    user_address: "567 Pine Court, Ottawa, ON",
    user_role: 2,
  },
  {
    username: "David Lee",
    user_email: "david.lee@example.com",
    user_password: "password789",
    user_telephone: 4567890123,
    user_address: "890 Maple Lane, Calgary, AB",
    user_role: 2,
  },
  {
    username: "Sophia Wang",
    user_email: "sophia.wang@example.com",
    user_password: "mysecurepassword",
    user_telephone: 5678901234,
    user_address: "123 Birch Street, Edmonton, AB",
    user_role: 2,
  },
  {
    username: "James Chen",
    user_email: "james.chen@example.com",
    user_password: "testpass123",
    user_telephone: 6789012345,
    user_address: "456 Cedar Avenue, Winnipeg, MB",
    user_role: 2,
  },
  {
    username: "Olivia Li",
    user_email: "olivia.li@example.com",
    user_password: "mypassword",
    user_telephone: 7890123456,
    user_address: "789 Oak Street, Quebec City, QC",
    user_role: 2,
  },
  {
    username: "Liam Martin",
    user_email: "liam.martin@example.com",
    user_password: "secure123",
    user_telephone: 8901234567,
    user_address: "234 Elm Lane, Hamilton, ON",
    user_role: 2,
  },
  {
    username: "Ava Garcia",
    user_email: "ava.garcia@example.com",
    user_password: "mypassword123",
    user_telephone: 9012345678,
    user_address: "567 Pine Road, Mississauga, ON",
    user_role: 2,
  },
]);